

server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: studentModule
        uri: http://localhost:8001/
        predicates:
        - Path=/student/**
      - id: courseModule
        uri: http://localhost:8002/
        predicates:
        - Path=/course/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka