


spring:
  application:
    name: eureka discovery service

server:
  port: 8091

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8091/eureka